/*
Programmer: Jeannie Zhang
Date: October 15, 2020
Program Name: Matching Game
Program Description: This program uses arrays to simulate a matching game
* A grid of cards will be displayed and the user is to select 2 cards at a time
* looking for matching cards. The goal of this game is to see how quickly
* the user can find all the matches.
*/
/**
 *
 * @author Jeannie
 */

import java.util.*;

import javax.swing.ImageIcon;

public class frmMatchingGame extends javax.swing.JFrame {

    /**
     * Creates new form frmMatchingGame
     */
    
    ArrayList <String> cards = new ArrayList();
    ArrayList <String> set = new ArrayList();
    ImageIcon a = new ImageIcon(getClass().getResource("match1.png"));
    ImageIcon b = new ImageIcon(getClass().getResource("match2.png"));
    ImageIcon c = new ImageIcon(getClass().getResource("match3.png"));
    ImageIcon d = new ImageIcon(getClass().getResource("match4.png"));
    ImageIcon e = new ImageIcon(getClass().getResource("match5.png"));
    ImageIcon f = new ImageIcon(getClass().getResource("match6.png"));
    ImageIcon g = new ImageIcon(getClass().getResource("match7.png"));
    ImageIcon h = new ImageIcon(getClass().getResource("match8.png"));
    ImageIcon back = new ImageIcon(getClass().getResource("matchback.png"));
    ImageIcon done = new ImageIcon(getClass().getResource("matchblank.png"));
    int count, c1, c2, card1, card2;
    int cardsLeft = 16;
    int[] change = new int[16];
    
    public frmMatchingGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainTitle = new javax.swing.JLabel();
        btnCard2 = new javax.swing.JButton();
        btnCard1 = new javax.swing.JButton();
        btnCard3 = new javax.swing.JButton();
        btnCard4 = new javax.swing.JButton();
        btnCard5 = new javax.swing.JButton();
        btnCard6 = new javax.swing.JButton();
        btnCard7 = new javax.swing.JButton();
        btnCard8 = new javax.swing.JButton();
        btnCard9 = new javax.swing.JButton();
        btnCard13 = new javax.swing.JButton();
        btnCard10 = new javax.swing.JButton();
        btnCard14 = new javax.swing.JButton();
        btnCard11 = new javax.swing.JButton();
        btnCard15 = new javax.swing.JButton();
        btnCard12 = new javax.swing.JButton();
        btnCard16 = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnGuessAgain = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtInstructions = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMainTitle.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblMainTitle.setForeground(new java.awt.Color(204, 0, 51));
        lblMainTitle.setText("Pokemon Matching Game");

        btnCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard2ActionPerformed(evt);
            }
        });

        btnCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard1ActionPerformed(evt);
            }
        });

        btnCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard3ActionPerformed(evt);
            }
        });

        btnCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard4ActionPerformed(evt);
            }
        });

        btnCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard5ActionPerformed(evt);
            }
        });

        btnCard6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard6ActionPerformed(evt);
            }
        });

        btnCard7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard7ActionPerformed(evt);
            }
        });

        btnCard8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard8ActionPerformed(evt);
            }
        });

        btnCard9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard9ActionPerformed(evt);
            }
        });

        btnCard13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard13ActionPerformed(evt);
            }
        });

        btnCard10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard10ActionPerformed(evt);
            }
        });

        btnCard14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard14ActionPerformed(evt);
            }
        });

        btnCard11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard11ActionPerformed(evt);
            }
        });

        btnCard15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard15ActionPerformed(evt);
            }
        });

        btnCard12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard12ActionPerformed(evt);
            }
        });

        btnCard16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchback.png"))); // NOI18N
        btnCard16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard16ActionPerformed(evt);
            }
        });

        btnPlay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnGuessAgain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGuessAgain.setText("Guess Again");
        btnGuessAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessAgainActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtInstructions.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txtInstructions.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInstructions.setText("Click the Play button to start. Make sure to click Guess Again after each guess.");
        txtInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(lblMainTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCard1)
                                            .addComponent(btnCard5))
                                        .addGap(118, 118, 118)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCard2)
                                            .addComponent(btnCard6))
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCard3)
                                            .addComponent(btnCard7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCard13)
                                            .addComponent(btnCard9))
                                        .addGap(118, 118, 118)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCard14)
                                            .addComponent(btnCard10))
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCard11)
                                            .addComponent(btnCard15))))
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCard8)
                                    .addComponent(btnCard4)
                                    .addComponent(btnCard12)
                                    .addComponent(btnCard16)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addComponent(btnGuessAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblMainTitle)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCard2)
                            .addComponent(btnCard3)
                            .addComponent(btnCard1))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCard6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCard7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCard5))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCard9)
                            .addComponent(btnCard11)
                            .addComponent(btnCard10))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCard13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCard14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCard15, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCard4)
                                .addGap(183, 183, 183))
                            .addComponent(btnCard8))
                        .addGap(73, 73, 73)
                        .addComponent(btnCard12)
                        .addGap(56, 56, 56)
                        .addComponent(btnCard16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuessAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(txtInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        
        //set change array
        for (int z=0; z<=15; z++){
            change [z]=1;
        }
        
        //assign cards at random
        String temp;
        for (int x=0; x<=7; x++){
            for (int y=1; y<=2; y++){
                temp = Integer.toString(x);
                set.add(temp);
            }
        }
        for (int x=0; x<=15; x++){
            double index = Math.floor(Math.random()*(16-x));
            int index1 = (int)index;
            cards.add(set.get(index1));
            set.remove(set.get(index1));
        }
    
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard1ActionPerformed
        String temp = cards.get(0);
        
        if (temp.equals("0")){
            btnCard1.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard1.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard1.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard1.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard1.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard1.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard1.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard1.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[0] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[0] = 0;
        }
        
    }//GEN-LAST:event_btnCard1ActionPerformed

    private void txtInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructionsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard2ActionPerformed
        String temp = cards.get(1);
        
        if (temp.equals("0")){
            btnCard2.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard2.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard2.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard2.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard2.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard2.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard2.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard2.setIcon(h);
        }
        
        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[1]=0;
        }
        else if(count==2){
            c2=Integer.parseInt(temp);
            change[1]=0;
        }

    }//GEN-LAST:event_btnCard2ActionPerformed

    private void btnCard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard3ActionPerformed
                String temp = cards.get(2);
        
        if (temp.equals("0")){
            btnCard3.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard3.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard3.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard3.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard3.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard3.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard3.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard3.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[2] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[2] = 0;
        }
        
    }//GEN-LAST:event_btnCard3ActionPerformed

    private void btnCard4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard4ActionPerformed
                String temp = cards.get(3);
        
        if (temp.equals("0")){
            btnCard4.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard4.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard4.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard4.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard4.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard4.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard4.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard4.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[3] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[3] = 0;
        }
        
    }//GEN-LAST:event_btnCard4ActionPerformed

    private void btnCard5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard5ActionPerformed
                String temp = cards.get(4);
        
        if (temp.equals("0")){
            btnCard5.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard5.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard5.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard5.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard5.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard5.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard5.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard5.setIcon(h);
        }
               
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[4] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[4] = 0;
        }
        
    }//GEN-LAST:event_btnCard5ActionPerformed

    private void btnCard6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard6ActionPerformed
                String temp = cards.get(5);
        
        if (temp.equals("0")){
            btnCard6.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard6.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard6.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard6.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard6.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard6.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard6.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard6.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[5] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[5] = 0;
        }
        
    }//GEN-LAST:event_btnCard6ActionPerformed

    private void btnCard7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard7ActionPerformed
                String temp = cards.get(6);
        
        if (temp.equals("0")){
            btnCard7.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard7.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard7.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard7.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard7.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard7.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard7.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard7.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[6] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[6] = 0;
        }
        
    }//GEN-LAST:event_btnCard7ActionPerformed

    private void btnCard8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard8ActionPerformed
                String temp = cards.get(7);
        
        if (temp.equals("0")){
            btnCard8.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard8.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard8.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard8.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard8.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard8.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard8.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard8.setIcon(h);
        }
                
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[7] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[7] = 0;
        }
        
    }//GEN-LAST:event_btnCard8ActionPerformed

    private void btnCard9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard9ActionPerformed
                String temp = cards.get(8);
        
        if (temp.equals("0")){
            btnCard9.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard9.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard9.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard9.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard9.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard9.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard9.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard9.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[8] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[8] = 0;
        }
        
    }//GEN-LAST:event_btnCard9ActionPerformed

    private void btnCard10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard10ActionPerformed
                String temp = cards.get(9);
        
        if (temp.equals("0")){
            btnCard10.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard10.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard10.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard10.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard10.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard10.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard10.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard10.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[9] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[9] = 0;
        }
        
    }//GEN-LAST:event_btnCard10ActionPerformed

    private void btnCard11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard11ActionPerformed
                String temp = cards.get(10);
        
        if (temp.equals("0")){
            btnCard11.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard11.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard11.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard11.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard11.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard11.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard11.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard11.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[10] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[10] = 0;
        }
        
    }//GEN-LAST:event_btnCard11ActionPerformed

    private void btnCard12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard12ActionPerformed
                String temp = cards.get(11);
        
        if (temp.equals("0")){
            btnCard12.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard12.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard12.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard12.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard12.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard12.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard12.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard12.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[11] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[11] = 0;
        }
        
    }//GEN-LAST:event_btnCard12ActionPerformed

    private void btnCard13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard13ActionPerformed
                String temp = cards.get(12);
        
        if (temp.equals("0")){
            btnCard13.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard13.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard13.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard13.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard13.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard13.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard13.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard13.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[12] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[12] = 0;
        }
        
    }//GEN-LAST:event_btnCard13ActionPerformed

    private void btnCard14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard14ActionPerformed
                String temp = cards.get(13);
        
        if (temp.equals("0")){
            btnCard14.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard14.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard14.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard14.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard14.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard14.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard14.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard14.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[13] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[13] = 0;
        }
        
    }//GEN-LAST:event_btnCard14ActionPerformed

    private void btnCard15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard15ActionPerformed
                String temp = cards.get(14);
        
        if (temp.equals("0")){
            btnCard15.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard15.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard15.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard15.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard15.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard15.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard15.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard15.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[14] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[14] = 0;
        }
        
    }//GEN-LAST:event_btnCard15ActionPerformed

    private void btnCard16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard16ActionPerformed
        String temp = cards.get(15);
        
        if (temp.equals("0")){
            btnCard16.setIcon(a);
        }
        else if(temp.equals("1")){
            btnCard16.setIcon(b);
        }
        else if(temp.equals("2")){
            btnCard16.setIcon(c);
        }
        else if(temp.equals("3")){
            btnCard16.setIcon(d);
        }
        else if(temp.equals("4")){
            btnCard16.setIcon(e);
        }
        else if(temp.equals("5")){
            btnCard16.setIcon(f);
        }
        else if(temp.equals("6")){
            btnCard16.setIcon(g);
        }
        else if(temp.equals("7")){
            btnCard16.setIcon(h);
        }
        
        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[15] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[15] = 0;
        }
        
    }//GEN-LAST:event_btnCard16ActionPerformed

    private void btnGuessAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessAgainActionPerformed
        
       count = 0;
       if(c1==c2){
           for (int y=1; y<=2; y++){
               if (change[0]==0){
                   btnCard1.setIcon(done);
                   btnCard1.setOpaque(false);
                   btnCard1.setContentAreaFilled(false);
                   btnCard1.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[0]=2;
               }
               else if (change[1]==0){
                   btnCard2.setIcon(done);
                   btnCard2.setOpaque(false);
                   btnCard2.setContentAreaFilled(false);
                   btnCard2.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[1]=2;
               }
               else if (change[2]==0){
                   btnCard3.setIcon(done);
                   btnCard3.setOpaque(false);
                   btnCard3.setContentAreaFilled(false);
                   btnCard3.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[2]=2;
               }
               else if (change[3]==0){
                   btnCard4.setIcon(done);
                   btnCard4.setOpaque(false);
                   btnCard4.setContentAreaFilled(false);
                   btnCard4.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[3]=2;
               }
               else if (change[4]==0){
                   btnCard5.setIcon(done);
                   btnCard5.setOpaque(false);
                   btnCard5.setContentAreaFilled(false);
                   btnCard5.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[4]=2;
               }
               else if (change[5]==0){
                   btnCard6.setIcon(done);
                   btnCard6.setOpaque(false);
                   btnCard6.setContentAreaFilled(false);
                   btnCard6.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[5]=2;
               }
               else if (change[6]==0){
                   btnCard7.setIcon(done);
                   btnCard7.setOpaque(false);
                   btnCard7.setContentAreaFilled(false);
                   btnCard7.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[6]=2;
               }
               else if (change[7]==0){
                   btnCard8.setIcon(done);
                   btnCard8.setOpaque(false);
                   btnCard8.setContentAreaFilled(false);
                   btnCard8.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[7]=2;
               }
               else if (change[8]==0){
                   btnCard9.setIcon(done);
                   btnCard9.setOpaque(false);
                   btnCard9.setContentAreaFilled(false);
                   btnCard9.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[8]=2;
               }
               else if (change[9]==0){
                   btnCard10.setIcon(done);
                   btnCard10.setOpaque(false);
                   btnCard10.setContentAreaFilled(false);
                   btnCard10.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[9]=2;
               }
               else if (change[10]==0){
                   btnCard11.setIcon(done);
                   btnCard11.setOpaque(false);
                   btnCard11.setContentAreaFilled(false);
                   btnCard11.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[10]=2;
               }
               else if (change[11]==0){
                   btnCard12.setIcon(done);
                   btnCard12.setOpaque(false);
                   btnCard12.setContentAreaFilled(false);
                   btnCard12.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[11]=2;
               }
               else if (change[12]==0){
                   btnCard13.setIcon(done);
                   btnCard13.setOpaque(false);
                   btnCard13.setContentAreaFilled(false);
                   btnCard13.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[12]=2;
               }
               else if (change[13]==0){
                   btnCard14.setIcon(done);
                   btnCard14.setOpaque(false);
                   btnCard14.setContentAreaFilled(false);
                   btnCard14.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[13]=2;
               }
               else if (change[14]==0){
                   btnCard15.setIcon(done);
                   btnCard15.setOpaque(false);
                   btnCard15.setContentAreaFilled(false);
                   btnCard15.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[14]=2;
               }
               else if (change[15]==0){
                   btnCard16.setIcon(done);
                   btnCard16.setOpaque(false);
                   btnCard16.setContentAreaFilled(false);
                   btnCard16.setBorderPainted(false);
                   cardsLeft = cardsLeft-1;
                   change[15]=2;
               }
           }
       }
       else{
           for(int y=1; y<=2; y++){
               if (change[0]==0){
                   btnCard1.setIcon(back);
                   change[0]=1;
               }
               else if(change[1]==0){
                   btnCard2.setIcon(back);
                   change[1]=1;
               }
               else if (change[2]==0){
                   btnCard3.setIcon(back);
                   change[2]=1;
               }
               else if (change[3]==0){
                   btnCard4.setIcon(back);
                   change[3]=1;
               }
               else if (change[4]==0){
                   btnCard5.setIcon(back);
                   change[4]=1;
               }
               else if (change[5]==0){
                   btnCard6.setIcon(back);
                   change[5]=1;
               }
               else if (change[6]==0){
                   btnCard7.setIcon(back);
                   change[6]=1;
               }
               else if (change[7]==0){
                   btnCard8.setIcon(back);
                   change[7]=1;
               }
               else if (change[8]==0){
                   btnCard9.setIcon(back);
                   change[8]=1;
               }
               else if (change[9]==0){
                   btnCard10.setIcon(back);
                   change[9]=1;
               }
               else if (change[10]==0){
                   btnCard11.setIcon(back);
                   change[10]=1;
               }
               else if (change[11]==0){
                   btnCard12.setIcon(back);
                   change[11]=1;
               }
               else if (change[12]==0){
                   btnCard13.setIcon(back);
                   change[12]=1;
               }
               else if (change[13]==0){
                   btnCard14.setIcon(back);
                   change[13]=1;
               }
               else if (change[14]==0){
                   btnCard15.setIcon(back);
                   change[14]=1;
               }
               else if (change[15]==0){
                   btnCard16.setIcon(back);
                   change[15]=1;
               }
           }
       }
       
       if (cardsLeft==0){
           txtInstructions.setText("Congratulations!");
       }
        
    }//GEN-LAST:event_btnGuessAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMatchingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMatchingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMatchingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMatchingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMatchingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCard1;
    private javax.swing.JButton btnCard10;
    private javax.swing.JButton btnCard11;
    private javax.swing.JButton btnCard12;
    private javax.swing.JButton btnCard13;
    private javax.swing.JButton btnCard14;
    private javax.swing.JButton btnCard15;
    private javax.swing.JButton btnCard16;
    private javax.swing.JButton btnCard2;
    private javax.swing.JButton btnCard3;
    private javax.swing.JButton btnCard4;
    private javax.swing.JButton btnCard5;
    private javax.swing.JButton btnCard6;
    private javax.swing.JButton btnCard7;
    private javax.swing.JButton btnCard8;
    private javax.swing.JButton btnCard9;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuessAgain;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JTextField txtInstructions;
    // End of variables declaration//GEN-END:variables
}
